### ISSUE TITLE
Add option for no GPIO?

### ISSUE THREAD

**Issue by niai** [mKeRix/hassio-repo#1]
Hi could you add an option to disable GPIO for people not running on a RPI?

I got this error when trying to run on an Ubuntu box

`18-07-30 01:09:52 ERROR (SyncWorker_1) [hassio.docker] Can't start addon_6e66619d_room-assistant: 500 Server Error: Internal Server Error ("error while creating mount source path '/sys/devices/platform/soc': mkdir /sys/devices/platform/soc: operation not permitted")`

**Comment by mKeRix** [comment]
Hey there,

this is unfortunately an Hass.io bug that I can’t really work around without inconveniencing some people. I’ve listed a fix on the ticket over on their repo: home-assistant/hassio#432

**Comment by niai** [comment]
That would be nice, if its not to much hassle to maintain for you. It would be a lot easier for my self and others like me, even though I am not sure meany people use HASSIO  the x86 architecture.

Thanks for the quick reply.

**Comment by mKeRix** [comment]
Just to let you know, if you haven't seen it yet: this issue has apparently been fixed in the current version of Hass.io, see home-assistant/hassio#432.
