### ISSUE TITLE
Addon not loading configuration

### ISSUE THREAD

**Issue by franfos** [mKeRix/hassio-repo#13]
I'm running room-assistant addon v2.13.0 on HASS v2021.2.2 and it looks like it's not loading my configuration.
No matter what I set, every time the output is the same:

> [15:11:55] INFO: Setting up Home Assistant configuration
[15:11:55] INFO: Starting room-assistant
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2/10/2021, 3:12:04 PM - info - IntegrationsModule: Loading integrations: none
2/10/2021, 3:12:05 PM - info - NestFactory: Starting Nest application...
2/10/2021, 3:12:06 PM - info - InstanceLoader: AppModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: ConfigModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: NestEmitterModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: IntegrationsModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: HttpModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: DiscoveryModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: PrometheusModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: ClusterModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: TerminusModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: ScheduleModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: EntitiesModule dependencies initialized
2/10/2021, 3:12:06 PM - info - InstanceLoader: StatusModule dependencies initialized
2/10/2021, 3:12:07 PM - info - RoutesResolver: EntitiesController {/entities}:
2/10/2021, 3:12:07 PM - info - RouterExplorer: Mapped {/entities, GET} route
2/10/2021, 3:12:07 PM - info - RoutesResolver: StatusController {/status}:
2/10/2021, 3:12:07 PM - info - RouterExplorer: Mapped {/status, GET} route
2/10/2021, 3:12:07 PM - info - RoutesResolver: PrometheusController {/metrics}:
2/10/2021, 3:12:07 PM - info - RouterExplorer: Mapped {/metrics, GET} route
2/10/2021, 3:12:07 PM - info - ConfigService: Loading configuration from /usr/lib/node_modules/room-assistant/dist/config/definitions/default.js, config/default.json, config/local.json
2/10/2021, 3:12:07 PM - error - ClusterService: Failed to start mdns discovery (dns service error: unknown)
2/10/2021, 3:12:07 PM - info - NestApplication: Nest application successfully started
2/10/2021, 3:12:08 PM - info - ClusterService: 3ef88635-room-assistant has been elected as leader
2/10/2021, 3:12:08 PM - info - EntitiesService: Refreshing entity states

This is the config for that output:

> global:
  instanceName: cambio
  integrations:
    - homeAssistant
cluster:
  weight: 5
  autoDiscovery: false
  peerAddresses:
    - '192.168.0.65:6425'
    - '192.168.0.25:6425'

I've also noticed these warnings in system's log:

> 21-02-10 14:11:42 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-10 14:11:42 WARNING (MainThread) [supervisor.addons.options] Unknown options cluster
21-02-10 14:11:46 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-10 14:11:46 WARNING (MainThread) [supervisor.addons.options] Unknown options cluster
21-02-10 14:11:46 WARNING (MainThread) [supervisor.addons.options] Unknown options global
21-02-10 14:11:46 WARNING (MainThread) [supervisor.addons.options] Unknown options cluster
21-02-10 14:11:54 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on mkerix/room-assistant-armv7 with version 2.13.0

Any idea what could be happening?

**Comment by mKeRix** [comment]
An un-announced breaking change by the Home Assistant Supervisor (home-assistant/supervisor#2540)broke the add-on (along with many other add-ons). You can find more details at mKeRix/room-assistant#501. In order to not spread the discussion too thin I will close this issue as duplicate and would ask you to continue talking over there. :)
