### ISSUE TITLE
upgrade to 2.18 error within home assitant

### ISSUE THREAD

**Issue by asucrews** [mKeRix/hassio-repo#23]
Hello, I get the below error when trying to upgrade to 2.18.0.

404 Client Error for http+docker://localhost/v1.40/images/create?tag=2.18.0&fromImage=mkerix%2Froom-assistant-aarch64: Not Found ("manifest for mkerix/room-assistant-aarch64:2.18.0 not found: manifest unknown: manifest unknown")

**Comment by mKeRix** [comment]
You were a tiny bit too fast :) The release build for the add-on images just finished around 15min ago. Upgrades should work now. Each time I release a new version it takes a little while to actually build and push the images, but the Home Assistant UI may already show it as an update.
