### ISSUE TITLE
Error in my log

### ISSUE THREAD

**Issue by mbrihed** [mKeRix/hassio-repo#5]
Hi!
Thanks for a great add-on!

After upgrading to 2.7.0 I get lots of faults in my log with the below message (I have xx:ed out the real BT MAC Address):

5/27/2020, 6:10:34 AM - error - BluetoothClassicService: Command failed: hcitool -i hci0 cc "xx:xx:xx:xx:xx:xx" && hcitool -i hci0 rssi "xx:xx:xx:xx:xx:xx"
Can't create connection: I/O error
Get connection info failed: No such file or directory

It was working fine before the upgrade.

Thanks

**Comment by mKeRix** [comment]
I just put out a new release (2.7.1) that fixes this issue - will be available as add-on in a few minutes, as soon as the CI finishes. Apologies for missing this!

**Comment by mbrihed** [comment]
Just upgraded and messages are gone! Thanks a lot and great support and work!
